version: '3.3'
services:
  web:
    image: php
    ports:
      - "80:80"
    container_name: php-container
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - php-network
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php-network
volumes:
  mysql:
networks:
  php-network: